config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post 'ratings/new'
  post 'orgs/contact'

  resources :orgs
  resources :ratings

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/org.rb
class Org < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :acronym, presence: true, uniqueness: true
	validates :scope, presence: true
	validates :description, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :org
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  def index
    @orgs = Org.all.paginate(page: params[:page], per_page: 10)
    if params[:noa] == "1"
      @orgs = Org.where("name like ?", "%" + params[:keyword] + "%").paginate(page: params[:page], per_page: 10)
    elsif params[:noa] == "2"
      @orgs = Org.where("acronym like ?", "%" + params[:keyword] + "%").paginate(page: params[:page], per_page: 10)
    elsif params[:noa] == "3"
      @orgs = Org.where("college like ?", "%" + params[:keyword] + "%").paginate(page: params[:page], per_page: 10)
    elsif params[:noa] == "4"
      @orgs = Org.where("department like ?", "%" + params[:keyword] + "%").paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    if params[:id] == "contact"
      render 'contact'
    else
      @org = Org.find(params[:id])
      @ratings = Rating.where(:org => @org).paginate(page: params[:page], per_page: 10)
      @ctot = 0
      @ptot = 0
      @stot = 0
      @atot = 0
      if @ratings.count > 0
        @ratings.each do |r|
          @ctot = @ctot + r.community
          @ptot = @ptot + r.purpose
          @stot = @stot + r.selfbenefit
          @atot = @atot + r.application
        end
        @ctot = (@ctot.to_f / @ratings.count)
        @ptot = (@ptot.to_f / @ratings.count)
        @stot = (@stot.to_f / @ratings.count)
        @atot = (@atot.to_f / @ratings.count)
        @otot = (@ctot + @ptot + @stot + @atot) / 4
        @org.update(:rating => @otot)
      end
    end
  end

  def new
    @org = Org.new
  end

  def create
    @org = Org.new(org_params)

    if @org.save
      redirect_to @org
    else
      render 'new'
    end
  end

  private
  def org_params
    params.require(:org).permit(:name, :acronym, :college, :department, :scope, :description, :noa, :keyword, :contact)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @org = Org.find(params[:id].to_i)
  end

  def create
    puts rating_params
    @org = Org.find(params[:org].to_i)
    @rating = Rating.new(rating_params)
    @rating.update(:org => @org)
    @rating.save
    redirect_to @org
  end

  private
  def rating_params
    params.require(:rating).permit(:community, :purpose, :selfbenefit, :application, :details, :org)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orgstopick</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orgs/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Orgs To Pick</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
  </head>
  <body>
    <div class="grid">
    <div class="ui fluid four item blue inverted menu">
    <div class="header item">Orgs to Pick</div>
    <a href="/orgs" class="item">  <i class="list icon"></i>  All Organizations </a>
    <a href="/orgs/new" class="item">  <i class="plus icon"></i>  Add an Organization </a>
    <%= form_tag(orgs_path, method: :get) do %>
    <div class="ui input">
      <%= text_field_tag :keyword, nil, placeholder: "Search..." %>
      <%= select_tag(:noa, options_for_select([["Name",1],["Acronym",2],["College",3],["Department",4]], params[:noa] ), class:"ui compact selection dropdown") %>
      <%= hidden_field_tag :search, 1 %>
      <%= submit_tag 'Search', class: "ui primary button" %>
    </div>
    <% end %>
    </div>
    </div>
    <br>

    <div class="ui grid">
    <div class="two wide column"></div>
    <div class="twelve wide column">
    <h1>List of Organizations</h1>

    <table class="ui striped table">
      <thead>
      <tr>
        <th>Acronym</th>
        <th>Name</th>
        <th>College</th>
        <th>Department</th>
        <th>Scope</th>
        <!--<th>Rating</th>-->
      </tr>
      </thead>

      <tbody>
      <% @orgs.each do |o| %>
        <tr>
          <td><%= link_to o.acronym, org_path(o) %> </td>
          <td><%= o.name %></td>
          <td><%= o.college %></td>
          <td><%= o.department %></td>
          <td><%= o.scope %></td>
          <!--<td><% if o.rating != nil %> <%= o.rating %> <% else %> N/A <% end %></td>-->
        </tr>
      <% end %>
      </tbody>
      <tfoot>
        <tr>
        <th colspan="6"><%= will_paginate @orgs, renderer: WillPaginateSemanticUi::ActionView::Renderer %> </th>
        </tr>
      </tfoot>
    </table>
    <p align="right">Got any questions/suggestions/problems?<br>
    Let me know: orgstopickinfo@gmail.com</p>
    </div>
    <div class="two wide column"></div>
    </div>
  </body>
</html>

app/views/orgs/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Orgs To Pick</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
  </head>
  <body>
    <div class="grid">
    <div class="ui fluid four item blue inverted menu">
    <div class="header item">Orgs to Pick</div>
    <a href="/orgs" class="item">  <i class="list icon"></i>  All Organizations </a>
    <a href="/orgs/new" class="item">  <i class="plus icon"></i>  Add an Organization </a>
    <%= form_tag(orgs_path, method: :get) do %>
    <div class="ui input">
      <%= text_field_tag :keyword, nil, placeholder: "Search..." %>
      <%= select_tag(:noa, options_for_select([["Name",1],["Acronym",2],["College",3],["Department",4]], params[:noa] ), class:"ui compact selection dropdown") %>
      <%= hidden_field_tag :search, 1 %>
      <%= submit_tag 'Search', class: "ui primary button" %>
    </div>
    <% end %>
    </div>
    </div>
    <br>

    <div class="ui grid">
    <div class="two wide column"></div>
    <div class="twelve wide column">
    <h1>Add Organization</h1>

    <% if @org.errors.any? %>
      <div class="ui error message">
        <ul class="list">
          <% @org.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with scope: :org, url: orgs_path, local: true do |form| %>
      <div class="ui form">
        * Full Name:
        <div class="field">
          <%= form.text_field :name, placeholder: "Orgs To Pick"%>
        </div>

        <div class="ui grid">
          <div class="four wide column">
            * Acronym:
            <div class="field">
              <%= form.text_field :acronym, placeholder: "OTP"%>
            </div>
          </div>

          <div class="four wide column">
            College:
            <div class="field">
              <%= form.text_field :college, placeholder: "Engineering"%>
            </div>
          </div>

          <div class="four wide column">
            Department:
            <div class="field">
              <%= form.text_field :department, placeholder: "DCS"%>
            </div>
          </div>

          <div class="four wide column">
            * Scope:
            <div class="field">
              <%= form.text_field :scope, placeholder: "(University Wide/For BSXX only)"%>
            </div>
          </div>
        </div>
        <br>

        * Description:
        <div class="field">
          <%= form.text_area :description, class: 'textarea', placeholder: "A database for UP Orgs"%>
        </div>

        Contact Details:
        <div class="field">
          <%= form.text_area :contact, class: 'textarea', placeholder: "Website/Email/Number"%>
        </div>

        * These fields are required

      <p>
          <%= form.submit('Submit', class: "ui primary button", data: {confirm: "Please double check all of the inputs above before clicking OK."}) %>
      </p>
    <% end %>
    </div>
    </div>
    <div class="two wide column"></div>
    </div>
  </body>
</html>

app/views/orgs/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Orgs To Pick</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
  </head>
  <body>
    <div class="grid">
    <div class="ui fluid four item blue inverted menu">
    <div class="header item">Orgs to Pick</div>
    <a href="/orgs" class="item">  <i class="list icon"></i>  All Organizations </a>
    <a href="/orgs/new" class="item">  <i class="plus icon"></i>  Add an Organization </a>
    <%= form_tag(orgs_path, method: :get) do %>
    <div class="ui input">
      <%= text_field_tag :keyword, nil, placeholder: "Search..." %>
      <%= select_tag(:noa, options_for_select([["Name",1],["Acronym",2],["College",3],["Department",4]], params[:noa] ), class:"ui compact selection dropdown") %>
      <%= hidden_field_tag :search, 1 %>
      <%= submit_tag 'Search', class: "ui primary button" %>
    </div>
    <% end %>
    </div>
    </div>
    <br>

    <div class="ui grid">
    <div class="two wide column"></div>
    <div class="twelve wide column">

      <div class="ui segments">
        <div class="ui blue inverted segment">
          <h1><%= @org.name %> (<%= @org.acronym %>)</h1>
        </div>
        <div class="ui segment">
          <p><strong>Description:</strong> <%= @org.description %></p>
        </div>
        <div class="ui horizontal segments">
          <div class="ui segment">
            <p><strong>Scope:</strong> <%= @org.scope %></p>
          </div>
          <div class="ui segment">
            <p><strong>College:</strong> <%= @org.college %></p>
          </div>
          <div class="ui segment">
            <p><strong>Department:</strong> <%= @org.department %></p>
          </div>
        </div>
        <div class="ui segment">
          <p><strong>Contact Details:</strong> <%= @org.contact %></p>
        </div>
      </div>

      <br>

    <!--

    <div class="ui five statistics">
      <div class="statistic">
        <div class="value">
          <% if @ratings.count > 0 %> <%= @otot %> <% else %> - <% end %><i class="chart pie icon"></i>
        </div>
        <div class="label">
          Overall
        </div>
      </div>
      <div class="statistic">
        <div class="value">
          <% if @ratings.count > 0 %> <%= @ctot %> <% else %> - <% end %><i class="users icon"></i>
        </div>
        <div class="label">
          Community
        </div>
      </div>
      <div class="statistic">
        <div class="value">
          <% if @ratings.count > 0 %> <%= @ptot %> <% else %> - <% end %><i class="bullseye icon"></i>
        </div>
        <div class="label">
          Purpose
        </div>
      </div>
      <div class="statistic">
        <div class="value">
          <% if @ratings.count > 0 %> <%= @stot %> <% else %> - <% end %><i class="user icon"></i>
        </div>
        <div class="label">
          Self-Benefit
        </div>
      </div>
      <div class="statistic">
        <div class="value">
          <% if @ratings.count > 0 %> <%= @atot %> <% else %> - <% end %><i class="clipboard list icon"></i>
        </div>
        <div class="label">
          Application Process
        </div>
      </div>
    </div>

    <table class="ui celled table">
      <thead>
      <tr>
          <th colspan="3"><h4 class="center aligned header"> Comments and Ratings </h4></th>
      </tr>
      <tr>
        <th colspan="2" class="four wide">Rating</th>
        <th class="twelve wide">Comment</th>
      </tr>
      </thead>

      <tbody>
      <% @ratings.each do |r| %>
        <tr>
          <td>Community:<br>
          Purpose:<br>
          Self-Benefit:<br>
          App Process:</td>

          <td><% r.community.to_i.times do  %> <i class="star icon"></i><% end %><% (5-r.community.to_i).times do  %> <i class="star outline icon"></i><% end %><br>
          <% r.purpose.to_i.times do  %> <i class="star icon"></i><% end %><% (5-r.purpose.to_i).times do  %> <i class="star outline icon"></i><% end %><br>
          <% r.selfbenefit.to_i.times do  %> <i class="star icon"></i><% end %><% (5-r.selfbenefit.to_i).times do  %> <i class="star outline icon"></i><% end %><br>
          <% r.application.to_i.times do  %> <i class="star icon"></i><% end %><% (5-r.application.to_i).times do  %> <i class="star outline icon"></i><% end %></td>

          <td><%= r.details %></td>
        </tr>
      <% end %>
      </tbody>
      <tfoot>
        <tr>
        <th colspan="3"><%= will_paginate @ratings, renderer: WillPaginateSemanticUi::ActionView::Renderer %> </th>
        </tr>
      </tfoot>
    </table>

    <%= form_with url: new_rating_path, local: true do |form| %>
        <%= hidden_field_tag :id, @org.id %>
        <div class="ui primary button" data-tooltip="Please be honest and avoid spamming comments."><%= form.submit 'Add Rating', class: 'ui primary button' %></div>
    <% end %>
     -->

    </div>
    <div class="two wide column"></div>
    </div>
  </body>
</html>

app/views/partials/header.html.erb
<div class="ui top fixed borderless menu" id="header_menu">
    <div class="item"><a id="header_text">Orgs To Pick</a></div>
        <div class="right menu">
            <div class="ui item">
                <div class="ui test button">Sign up</div>
            </div>
        </div>
</div>

<div class="ui test modal">
  <i class="close icon"></i>
  <div class="header">
    Log In
  </div>
  <div class="content">
    Someshit
  </div>
</div>

app/views/partials/modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= yield %>
    </div>
  </div>
</div>

app/views/ratings/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Orgs To Pick</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
  </head>
  <body>
    <div class="grid">
    <div class="ui fluid four item blue inverted menu">
    <div class="header item">Orgs to Pick</div>
    <a href="/orgs" class="item">  <i class="list icon"></i>  All Organizations </a>
    <a href="/orgs/new" class="item">  <i class="plus icon"></i>  Add an Organization </a>
    <%= form_tag(orgs_path, method: :get) do %>
    <div class="ui input">
      <%= text_field_tag :keyword, nil, placeholder: "Search..." %>
      <%= select_tag(:noa, options_for_select([["Name",1],["Acronym",2],["College",3],["Department",4]], params[:noa] ), class:"ui compact selection dropdown") %>
      <%= hidden_field_tag :search, 1 %>
      <%= submit_tag 'Search', class: "ui primary button" %>
    </div>
    <% end %>
    </div>
    </div>
    <br>

    <div class="ui grid">
    <div class="two wide column"></div>
    <div class="twelve wide column">
    <h1>Rate <%=@org.name%> </h1>

    <%= form_with scope: :rating, url: ratings_path, local: true do |form| %>
    <div class="ui form">
      <%= hidden_field_tag :org, @org.id %>

      <div class="ui cards">
        <div class="card">
          <div class="content">
            <div class="header">Community</div>
            <div class="description">
              The general feeling when you're with the other members
            </div>
            <div class="extra">
              1<%= form.range_field :community, in: 1..5 %>5
            </div>
          </div>
        </div>
        <div class="card">
          <div class="content">
            <div class="header">Self-benefit</div>
            <div class="description">
              The skills and other gains you have acquired since joining
            </div>
            <div class="extra">
              1<%= form.range_field :selfbenefit, in: 1..5 %>5
            </div>
          </div>
        </div>
        <div class="card">
          <div class="content">
            <div class="header">Purpose</div>
            <div class="description">
              The quality and significance of the objectives of the organization
            </div>
            <div class="extra">
              1<%= form.range_field :purpose, in: 1..5 %>5
            </div>
          </div>
        </div>
        <div class="card">
          <div class="content">
            <div class="header">Application Process</div>
            <div class="description">
              Reasonability and relevance of the application process
            </div>
            <div class="extra">
              1<%= form.range_field :application, in: 1..5 %>5
            </div>
          </div>
        </div>
      </div>

      <p>
        Details:
        <div class="field">
          <%= form.text_area :details, class: 'textarea', placeholder: "Write something here"%>
        </div>
      </p>

      <p>
        <%= form.submit('Submit', class: "ui primary button", data: {confirm: "By clicking OK you agree that all of your inputs are sincere."}) %>
        <%= link_to "Back", org_path(@org) %>
      </p>
      </div>
    <% end %>
    </div>
    <div class="two wide column"></div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Orgs To Pick</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
  </head>
  <body>
      <!--MAIN CONTENT-->
      <div class="ui items">
      <div class="middle aligned content">
          <h1 align = "center"> ORGS TO PICK </h1>
          <p align = "center">A database of organizations in UP Diliman <br> Inspired by RUPP </p>
              <center>
                <%= form_tag(orgs_path, method: :get) do %>
                <div class="ui input">
                  <%= text_field_tag :keyword, nil, placeholder: "Search..." %>
                  <%= select_tag(:noa, options_for_select([["Name",1],["Acronym",2],["College",3],["Department",4]], params[:noa] ), class:"ui compact selection dropdown") %>
                  <%= hidden_field_tag :search, 1 %>
                  <%= submit_tag 'Search', class: "ui primary button" %>
                </div>
                <br><br>
                <a href="/orgs" class="ui right labeled icon blue button">  <i class="list icon"></i>  All Organizations </a>
                <a href="/orgs/new" class="ui right labeled icon blue button">  <i class="plus icon"></i>  Add an Organization </a>
                <% end %>
              </center>
          </div>
          </div>

  </body>
  <footer>
    <center><p>2019 OrgsToPick v.1.0</p></center>
  </footer>
</html>